### ISSUE TITLE
Issue on GKE-NV project when defining prefix and cluster_version_prefix variable

### ISSUE THREAD

**Issue by JavierLagosChanclon** [glovecchi0/neuvector-tf#8]
I have noticed that the Terraform deployment script fails when both prefix and cluster_version_prefix variables have been defined. 

Basically, at some point during TF execution, the script called first_setup.sh is executed and there are some variables that are receiving more than 1 value when it is expected to receive only 1 due to the definition of both variables in the TF vars file.

**Comment by JavierLagosChanclon** [comment]
I have been doing some successfully deployments after modifying all grep commands inside the first_setup.sh script from 
```
grep -i prefix
``` 

to

```
grep -i "^prefix"
```

**Comment by glovecchi0** [comment]
PR merged!

**Comment by JavierLagosChanclon** [comment]
The issue can be closed. Thanks Giovanni.
